export const TileFamilyCode = {
    PIN: "pin",
    SEN: "sen",
    MAN: "man",
    WIND: "wind",
    DRAGON: "dragon",
    SEASON: "season",
    FLOWER: "flower",
    ART: "art",
    NOBLE_PROFESSION: "noble_profession",
    ANIMAL: "animal",
    CLOWN: "clown",
    GENERAL_PURPOSE_JOKER: "general_purpose_joker",
    SUIT_RESTRICTED_JOKER: "suit_restricted_joker",
    RANK_RESTRICTED_JOKER: "rank_restricted_joker",
};
